test:
  image: alpine:edge
  tags:
    - docker-alpine
    - x86_64
  before_script:
    - apk add cargo build-base git python3-dev
  script:
    - |
      for space in test_workspaces/*; do
        echo "==> testing $space";
        (cd "$space"; cargo run --bin gclient sync --no_history);
      done
