pipeline:
  test:
    image: distroless.dev/alpine-base:latest
    commands:
      # fix repo list
      - |
        echo "https://alpine.sakamoto.pl/alpine/edge/main
        https://alpine.sakamoto.pl/alpine/edge/community" > /etc/apk/repositories
      # install system dependencies
      - apk update
      - apk add --no-cache cargo build-base git openssl-dev protoc python3-dev
      # install cargo dependencies
      - cargo fetch --locked
      # build
      - cargo build --frozen --bin download_from_google_storage
      - cargo build --frozen --bin gclient
      # unit tests
      - cargo test
