pipeline:
  test:
    image: distroless.dev/alpine-base:latest
    commands:
      # fix repo list
      - |
        echo "https://alpine.sakamoto.pl/alpine/edge/main
        https://alpine.sakamoto.pl/alpine/edge/community" > /etc/apk/repositories
      # install system dependencies
      - apk update
      - apk add --no-cache cargo build-base git openssl-dev protobuf-dev protoc python3-dev
      # install cargo dependencies
      - cargo fetch --locked
      # build
      - cargo build --frozen --release --bin gclient
      # unit tests
      - cargo test --release
      # integration tests
      - |
        for space in test_workspaces/*; do
          echo "==> testing $space";
          (cd "$space"; ../../target/release/gclient sync --no-history);
        done
