pipeline:
  test:
    image: alpine:edge
    commands:
      - apk add cargo build-base git python3-dev
      - |
        for space in test_workspaces/*; do
          echo "==> testing $space";
          (cd "$space"; cargo run --bin gclient sync --no-history);
        done
