[package]
name = "teapot_tools"
version = "0.1.0"
edition = "2021"
description = "Kind-of replacement for depot_tools (gclient)"
authors = ["Lauren N. Liberda <lauren@selfisekai.rocks>"]
repository = "https://gitlab.com/selfisekai/teapot_tools"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gclient"

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.6", features = ["derive"] }
linya = "0.3.0"
path-absolutize = "3.0.13"
pyo3 = { version = "0.16.5", features = ["auto-initialize", "macros", "serde"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
smart-default = "0.6.0"
url = "2.2.2"
