[package]
name = "teapot_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bins]]
name = "gclient"

[dependencies]
anyhow = "1.0.58"
pyo3 = { version = "0.16.5", features = ["auto-initialize", "macros", "serde"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
smart-default = "0.6.0"
